# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  mssqldb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssqldb
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssqldb_data:/var/opt/mssql
